---
time:
  - platform: sntp
    on_time:
      - cron: "0 30 3 * * 1" # Sunday at 3:30:00
        then:
          - logger.log: "Auto-restart triggered by schedule"
          - button.press: restart_button