---
binary_sensor:
  - platform: status
    id: status_sensor
    name: Status
    entity_category: diagnostic

button:
  - platform: restart
    name: Restart
    id: restart_button
    icon: mdi:restart
    entity_category: config

sensor:
  - platform: uptime
    type: seconds
    id: uptime_sensor
    name: Uptime
    entity_category: diagnostic