---
substitutions:
  time_timezone: "America/New_York"

time:
  - platform: sntp
    id: time_sntp
    timezone: "${time_timezone}"
    servers:
      - time1.internal.greyrock.io
      - time2.internal.greyrock.io
      - time3.internal.greyrock.io
