substitutions:
  device_name: bt-proxy-garage
  friendly_name: BT Proxy - Garage
  api_key: !secret bt_proxy_garage_api_key
  ota_password: !secret bt_proxy_garage_ota_password

packages:
  device: !include "common/Seeed xiao ESP32-c3 base.yaml"