substitutions:
  device_name: bt-proxy-office
  friendly_name: BT Proxy - Office
  api_key: !secret bt_proxy_office_api_key
  ota_password: !secret bt_proxy_office_ota_password

packages:
  device: !include "common/Seeed xiao ESP32-c3 base.yaml"