substitutions:
  device_name: bt-proxy-dining-room
  friendly_name: BT Proxy - Dining Room
  api_key: !secret bt_proxy_dining_room_api_key
  ota_password: !secret bt_proxy_dining_room_ota_password

packages:
  device: !include "common/Seeed xiao ESP32-c3 base.yaml"
