---
substitutions:
  system_name: dining-room-reterminal-e1001
  friendly_name: Dining Room - Weather Display
  device_description: Seeed reTerminal E1001 ePaper Weather Display
  api_key: !secret guest_wifi_display_api_key
  ota_password: !secret guest_wifi_display_ota_password

packages:
  device: !include reterminal-e1001/base.yaml