---
substitutions:
  system_name: garage-ratgdo-todd
  friendly_name: Garage - Ratgdo (Todd)
  device_description: ratgdo v2.5 ESP8266 Garage Door Controller
  api_key: !secret garage_ratgdo_todd_api_key

packages:
  ratgdo: github://ratgdo/esphome-ratgdo/v25board_esp8266_d1_mini_lite.yaml@main