---
substitutions:
  system_name: hvac-game-room
  friendly_name: HVAC - Game Room
  device_description: Mitsubishi CN105 ESP8266 Heat Pump
  remote_temp_sensor: sensor.gameroom_temp_728d_temperature
  api_key: !secret hvac_game_room_api_key

packages:
  device: !include hvac-cn105/base.yaml