---
substitutions:
  system_name: hvac-kitchen
  friendly_name: HVAC - Kitchen
  device_description: Mitsubishi CN105 ESP8266 Heat Pump
  remote_temp_sensor: sensor.kitchen_temp_775f_temperature
  api_key: !secret hvac_kitchen_api_key

packages:
  device: !include hvac-cn105/base.yaml