---
substitutions:
  system_name: hvac-office
  friendly_name: HVAC - Office
  device_description: Mitsubishi CN105 ESP8266 Heat Pump
  remote_temp_sensor: sensor.office_temp_289d_temperature
  api_key: !secret hvac_office_api_key

packages:
  device: !include hvac-cn105/base.yaml