---
substitutions:
  system_name: hvac-master-bedroom
  friendly_name: HVAC - Master Bedroom
  device_description: Mitsubishi CN105 ESP8266 Heat Pump
  remote_temp_sensor: sensor.mbr_temp_46f8_temperature
  api_key: !secret hvac_master_bedroom_api_key

packages:
  device: !include hvac-cn105/base.yaml