---
substitutions:
  system_name: office-ceiling-2
  friendly_name: Office Ceiling 2
  device_description: Athom GU10 RGBWW Smart Bulb
  api_key: !secret office_ceiling_2_api_key
  project_name: "office-ceiling-2"
  project_version: "1.0.0"
  light_restore_mode: "RESTORE_DEFAULT_ON"
  color_interlock: "true"

packages:
  device: !include athom-gu10/base.yaml