---
substitutions:
  system_name: tubeszb-efr32-mgm24-2023
  friendly_name: TubesZB - Zigbee Coordinator (MGM24)
  device_description: TubesZB MGM24 Zigbee Coordinator
  api_key: !secret zigbee_coordinator_api_key

api:
  encryption:
    key: ${api_key}

packages:
  tubezb: github://tube0013/TubesZB-ESPHome-Builder/manifests/tubeszb-efr32-mgm24-2023.yaml@main