---
substitutions:
  system_name: tubeszb-zw
  friendly_name: TubesZB - Z-Wave Coordinator
  device_description: TubesZB Z-Wave Coordinator
  api_key: !secret zwave_coordinator_api_key

api:
  encryption:
    key: ${api_key}

packages:
  tubezb: github://tube0013/TubesZB-ESPHome-Builder/manifests/tubeszb-2026-zw.yaml@main