---
name: Lint

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

concurrency:
  group: ${{ forgejo.ref }}-${{ forgejo.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Get changed files
        id: changed-files
        uses: https://github.com/bjw-s-labs/action-changed-files@a9a36fb08ce06db9b02fbd8026cc2c0945eb9841 # v0.6.0
        with:
          patterns: |-
            **/*.yaml
            **/*.yml

      - name: Install yamllint
        if: steps.changed-files.outputs.changed_files != '[]'
        shell: bash
        run: |
          pipx install yamllint

      - name: Run yamllint
        if: steps.changed-files.outputs.changed_files != '[]'
        shell: bash
        run: |-
          yamllint --config-file .yamllint.yaml --format github ${{ join(fromJSON(steps.changed-files.outputs.changed_files), ' ') }}